; M5GO を PC と StampFly の中継機にする
; PC ──USBシリアル──> M5GO ──ESP-NOW──> StampFly

[env:m5go]
platform = espressif32@6.9.0
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 115200          ; これより速いと M5GO では失敗した実績あり
lib_deps = m5stack/M5Unified@^0.2.2
build_flags = -DCORE_DEBUG_LEVEL=0
